// Project config
const ProjectConfig = {
  DATABASE_URL: "https://newfreedom-637b5.firebaseio.com",
  STORAGE_BUCKET: "newfreedom-637b5-210443dcd854",
  PROJECT_ID: "newfreedom-637b5",
};

// Firestore collection names (existing)
const POSTS_COLLECTION = "posts";
const INVITES_COLLECTION = "invites";
const INVITE_REQUESTS_COLLECTION = "inviteRequests";
const MESSAGES_COLLECTION = "messages";
const USERS_COLLECTION = "users";
const SUSPENDED_USERS_COLLECTION = "suspendedUsers";
const DELETED_USERS_COLLECTION = "deletedUsers";
const MODERATION_REPORTS_COLLECTION = "moderationReports";

// Lane 1: Re-Entry collections
const GOALS_COLLECTION = "goals";
const DOCUMENTS_COLLECTION = "documents";
const ACTION_PLANS_COLLECTION = "action_plans";
const APPOINTMENTS_COLLECTION = "appointments";
const JOB_APPLICATIONS_COLLECTION = "job_applications";
const BUDGETS_COLLECTION = "budgets";

// Lane 2: Step Experience collections
const COURSES_COLLECTION = "courses";
const COURSE_MODULES_COLLECTION = "course_modules";
const USER_PROGRESS_COLLECTION = "user_progress";
const JOURNAL_ENTRIES_COLLECTION = "journal_entries";
const ACHIEVEMENTS_COLLECTION = "achievements";

// Lane 3: My Struggle collections
const COMMENTS_COLLECTION = "comments";
const RESOURCES_COLLECTION = "resources";
const MENTOR_MATCHES_COLLECTION = "mentor_matches";
const DONATIONS_COLLECTION = "donations";

// Shared collections
const CONVERSATIONS_COLLECTION = "conversations";
const NOTIFICATIONS_COLLECTION = "notifications";
const ASSESSMENTS_COLLECTION = "assessments";

// Firestore prod collection names
const ProdCollections = [
  POSTS_COLLECTION,
  INVITES_COLLECTION,
  INVITE_REQUESTS_COLLECTION,
  MESSAGES_COLLECTION,
  USERS_COLLECTION,
  SUSPENDED_USERS_COLLECTION,
  DELETED_USERS_COLLECTION,
  MODERATION_REPORTS_COLLECTION,
  GOALS_COLLECTION,
  DOCUMENTS_COLLECTION,
  ACTION_PLANS_COLLECTION,
  APPOINTMENTS_COLLECTION,
  JOB_APPLICATIONS_COLLECTION,
  BUDGETS_COLLECTION,
  COURSES_COLLECTION,
  COURSE_MODULES_COLLECTION,
  USER_PROGRESS_COLLECTION,
  JOURNAL_ENTRIES_COLLECTION,
  ACHIEVEMENTS_COLLECTION,
  COMMENTS_COLLECTION,
  RESOURCES_COLLECTION,
  MENTOR_MATCHES_COLLECTION,
  DONATIONS_COLLECTION,
  CONVERSATIONS_COLLECTION,
  NOTIFICATIONS_COLLECTION,
  ASSESSMENTS_COLLECTION,
];

// Firestore data types
type FirestoreTypes = "string" | "number" | "boolean" | "array" | "date";

export {
  POSTS_COLLECTION,
  INVITES_COLLECTION,
  INVITE_REQUESTS_COLLECTION,
  MESSAGES_COLLECTION,
  USERS_COLLECTION,
  SUSPENDED_USERS_COLLECTION,
  DELETED_USERS_COLLECTION,
  MODERATION_REPORTS_COLLECTION,
  GOALS_COLLECTION,
  DOCUMENTS_COLLECTION,
  ACTION_PLANS_COLLECTION,
  APPOINTMENTS_COLLECTION,
  JOB_APPLICATIONS_COLLECTION,
  BUDGETS_COLLECTION,
  COURSES_COLLECTION,
  COURSE_MODULES_COLLECTION,
  USER_PROGRESS_COLLECTION,
  JOURNAL_ENTRIES_COLLECTION,
  ACHIEVEMENTS_COLLECTION,
  COMMENTS_COLLECTION,
  RESOURCES_COLLECTION,
  MENTOR_MATCHES_COLLECTION,
  DONATIONS_COLLECTION,
  CONVERSATIONS_COLLECTION,
  NOTIFICATIONS_COLLECTION,
  ASSESSMENTS_COLLECTION,
  ProdCollections,
  FirestoreTypes,
  ProjectConfig,
};
